---
- name: Install neovim dependencies
  become: true
  package:
    name: "{{ item }}"
    state: present
  loop:
    - fzf
    - git
    - ripgrep
    - fd
  ignore_errors: true

- name: Install neovim dependencies (fd-find)
  become: true
  package:
    name:
      - fd-find
    state: present
  ignore_errors: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or ansible_distribution == 'Fedora'
