---
- name: "Customizing Linux"
  hosts: localhost
  connection: local
  roles:
    - role: "roles/configure-tmux"
    - role: "roles/configure-neovim"
    - role: "roles/configure-alacritty"
    - role: "roles/configure-rofi"
    - role: "roles/configure-fonts"
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ ansible_user_id }}"
    - role: "roles/configure-zsh"
    - role: "roles/configure-nvm"
    - role: gantsign.visual-studio-code
      users:
        - username: "{{ ansible_user_id }}"
    - role: gantsign.golang
      golang_gopath: '$HOME/go'
    - role: andrewrothstein.gcc-toolbox
    - role: "roles/configure-gnome"
    - role: petermosmans.customize-gnome
  vars:
    gnome_dconf:
      - key: /org/gnome/desktop/background/picture-uri
        value: "'file:///home/{{ gnome_user }}/.config/background.jpg'"
      - key: /org/gnome/desktop/interface/monospace-font-name
        value: '"CaskaydiaCove Nerd Font Bold 10"'
      - key: /org/gnome/desktop/interface/document-font-name
        value: '"CaskaydiaCove Nerd Font SemiBold 11"'
      - key: /org/gnome/desktop/interface/font-name
        value: '"CaskaydiaCove Nerd Font 11"'
      - key: /org/gnome/desktop/wm/preferences/titlebar-font
        value: '"CaskaydiaCove Nerd Font Bold 11"'
      - key: /org/gnome/desktop/wm/preferences/button-layout
        value: "'appmenu:minimize,maximize,close'"
    gnome_extensions:
      - id: 615
        enable: yes
      - id: 5338
        enable: yes
      - id: 307
        enable: yes
      - id: 744
        enable: yes
      - id: 750
        enable: yes
      - id: 1460
        enable: yes
      - id: 19
        enable: yes
    gnome_gsettings:
      - schema: org.gnome.shell.extensions.aylurs-widgets
        schemadir: ~/.local/share/gnome-shell/extensions/widgets@aylur/schemas
        key: battery-bar
        value: 'false'
      - schema: org.gnome.shell.extensions.aylurs-widgets
        schemadir: ~/.local/share/gnome-shell/extensions/widgets@aylur/schemas
        key: dash-board
        value: 'false'
      - schema: org.gnome.shell.extensions.aylurs-widgets
        schemadir: ~/.local/share/gnome-shell/extensions/widgets@aylur/schemas
        key: media-player
        value: 'false'
      - schema: org.gnome.shell.extensions.aylurs-widgets
        schemadir: ~/.local/share/gnome-shell/extensions/widgets@aylur/schemas
        key: date-menu-date-format
        value: '"%a %b %d %H:%M"'
      - schema: org.gnome.shell.extensions.aylurs-widgets
        schemadir: ~/.local/share/gnome-shell/extensions/widgets@aylur/schemas
        key: date-menu-show-events
        value: 'false'
      - schema: org.gnome.shell.extensions.aylurs-widgets
        schemadir: ~/.local/share/gnome-shell/extensions/widgets@aylur/schemas
        key: date-menu-show-media
        value: 'false'
      - schema: org.gnome.shell.extensions.aylurs-widgets
        schemadir: ~/.local/share/gnome-shell/extensions/widgets@aylur/schemas
        key: date-menu-show-system-levels
        value: 'false'
      - schema: org.gnome.shell.extensions.aylurs-widgets
        schemadir: ~/.local/share/gnome-shell/extensions/widgets@aylur/schemas
        key: date-menu-show-weather
        value: 'false'
      - schema: org.gnome.shell.extensions.aylurs-widgets
        schemadir: ~/.local/share/gnome-shell/extensions/widgets@aylur/schemas
        key: date-menu-hide-stock-mpris
        value: 'true'
      - schema: org.gnome.shell.extensions.aylurs-widgets
        schemadir: ~/.local/share/gnome-shell/extensions/widgets@aylur/schemas
        key: date-menu-hide-notifications
        value: 'true'
      - schema: org.gnome.shell.extensions.aylurs-widgets
        schemadir: ~/.local/share/gnome-shell/extensions/widgets@aylur/schemas
        key: quick-settings-style
        value: 3
      - schema: org.gnome.shell.extensions.aylurs-widgets
        schemadir: ~/.local/share/gnome-shell/extensions/widgets@aylur/schemas
        key: quick-settings-show-system-levels
        value: 'false'
      - schema: org.gnome.shell.extensions.aylurs-widgets
        schemadir: ~/.local/share/gnome-shell/extensions/widgets@aylur/schemas
        key: quick-settings-show-media
        value: 'false'
      - schema: org.gnome.shell.extensions.aylurs-widgets
        schemadir: ~/.local/share/gnome-shell/extensions/widgets@aylur/schemas
        key: quick-settings-show-wired
        value: 'true'
      - schema: org.gnome.shell.extensions.aylurs-widgets
        schemadir: ~/.local/share/gnome-shell/extensions/widgets@aylur/schemas
        key: quick-settings-show-network-bt
        value: 'true'
      - schema: org.gnome.shell.extensions.aylurs-widgets
        schemadir: ~/.local/share/gnome-shell/extensions/widgets@aylur/schemas
        key: quick-settings-show-airplane
        value: 'true'
      - schema: org.gnome.shell.extensions.vitals
        schemadir: ~/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com/schemas
        key: show-voltage
        value: 'false'
      - schema: org.gnome.shell.extensions.vitals
        schemadir: ~/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com/schemas
        key: show-fan
        value: 'false'
      - schema: org.gnome.shell.extensions.vitals
        schemadir: ~/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com/schemas
        key: show-system
        value: 'false'
      - schema: org.gnome.shell.extensions.vitals
        schemadir: ~/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com/schemas
        key: show-storage
        value: 'false'
      - schema: org.gnome.shell.extensions.vitals
        schemadir: ~/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com/schemas
        key: show-battery
        value: 'false'
    gtk_version: 4.0
