---
- name: "Customizing Linux"
  hosts: localhost
  connection: local
  roles:
    - role: "roles/configure-tmux"
    - role: "roles/configure-neovim"
    - role: "roles/configure-alacritty"
    - role: "roles/configure-rofi"
    - role: "roles/configure-fonts"
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ ansible_user_id }}"
      plugins:
        - zsh-autosuggestions
        - zsh-syntax-highlighting
    - role: "roles/configure-zsh"
    - role: "roles/configure-nvm"
    - role: gantsign.visual-studio-code
      users:
        - username: "{{ ansible_user_id }}"
    - role: gantsign.golang
      golang_gopath: '$HOME/go'
    - role: andrewrothstein.gcc-toolbox