---
- name: "Customizing Linux"
  hosts: localhost
  connection: local
  roles:
    - role: "roles/configure-tmux"
    - role: "roles/configure-neovim"
    - role: gantsign.visual-studio-code
      users:
        - username: "{{ ansible_user_id }}"
