---
roles:
  - name: gantsign.visual-studio-code
  - name: gantsign.oh-my-zsh
  - name: gantsign.golang
  - name: andrewrothstein.gcc-toolbox
  - name: petermosmans.customize-gnome

collections:
  - name: community.general