---
- set_fact:
    font_directory: ~/.local/share/fonts

- name: Install fontconfig
  become: true
  package:
    state: present
    name: fontconfig

- name: Creates /tmp/CascadiaCode-fonts
  file:
    path: /tmp/CascadiaCode-fonts
    state: directory

- name: Set /tmp/CascadiaCode-fonts directory ownership
  file:
    dest: /tmp/CascadiaCode-fonts
    state: directory
    owner: "{{ ansible_user_id }}"

- name: Download CascadiaCode
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/CascadiaCode.zip
    dest: /tmp/CascadiaCode-fonts
    mode: 
    remote_src: yes

- name: Copy fonts
  command: cp -r /tmp/CascadiaCode-fonts/ {{ font_directory }}

- name: Set fonts directory ownership
  file:
    dest: "{{ font_directory }}"
    state: directory
    owner: "{{ ansible_user_id }}"

- name: Reset font cache
  command: fc-cache -f {{ font_directory }}