---
- set_fact:
    configs_directory: ~/.config

- name: Creates ~/.config/alacritty
  file:
    path: ~/.config/alacritty
    state: directory

- name: Set ~/.config/alacritty directory ownership
  file:
    dest: ~/.config/alacritty
    state: directory
    owner: "{{ ansible_user_id }}"

- name: Copy alacritty configs
  copy:
    src: "{{ role_path }}/files/alacritty"
    dest: "{{ configs_directory }}"
    owner: "{{ ansible_user_id }}"